<a href="https://colab.research.google.com/github/Thotasaiteja2004/python-for-data-structures/blob/main/22-08-25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
fp=open("example.txt","w")
#write text to file
fp.write("hello,B-tech students!\n")
fp.write("This is file handling in python.\n")
fp.write("sr university")
fp.write("saiteja")
#close file
fp.close()
print("data written successfully!")
#reading from a file
#open file in read mode
file=open("example.txt","r")
#read entire content
content=file.read()
print("file content:\n",content)
#close file
file.close()
#reading line by line
file=open("example.txt","r")
#read frist line
line1=file.readline()
print("frist line:",line1)
#read remaining lines
line2=file.readline()
print("second line:",line2)
line3=file.readline()
print("thrid line:",line3)
file.close()
#reading all lines into a list
file=open("example.txt","r")
lines=file.readlines()
print("all lines as list:",lines)
file.close()
#appending data to an existing file
file=open("example.txt","a")
file.write("appending new data...\n")
file.close()
#using with statement(best practise)
with open("example.txt","r")as fp:
    data=fp.read()
    print(data)
#working with csv files
import csv
#writing to csv
with open("data.csv","w",newline='')as fp:
    wr=csv.writer(fp)
    wr.writerows([["Name","Age","Course"],["aaa",22,"Cse"],["bbb",20,"Ece"]])
#reading from csv
with open("data.csv","r")as file:
    re=csv.reader(file)
    for row in re:
        print(row)






data written successfully!
file content:
 hello,B-tech students!
This is file handling in python.
sr universitysaiteja
frist line: hello,B-tech students!

second line: This is file handling in python.

thrid line: sr universitysaiteja
all lines as list: ['hello,B-tech students!\n', 'This is file handling in python.\n', 'sr universitysaiteja']
hello,B-tech students!
This is file handling in python.
sr universitysaitejaappending new data...

['Name', 'Age', 'Course']
['aaa', '22', 'Cse']
['bbb', '20', 'Ece']


In [14]:
import numpy as np
#1d array
arr1=np.array([1,2,3,4])
print("1d array:",arr1)
#2d array
arr2=np.array([[1,2,3],[4,5,6]])
print("2d array:\n",arr2)
#zero array
zero_arr=np.zeros((3,3))
print("zero array:\n",zero_arr)
#ones array
ones_arr=np.ones((2,4))
print("ones array:\n",ones_arr)
#range of numbers
range_arr=np.arange(0,10,2)#
#start,stop,Step # This line is causing the error
print("range array:",range_arr)
#random array
rand_arr=np.random.rand(3,3)
print("random array:\n",rand_arr)

1d array: [1 2 3 4]
2d array:
 [[1 2 3]
 [4 5 6]]
zero array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
range array: [0 2 4 6 8]
random array:
 [[0.23524281 0.55269996 0.55881436]
 [0.36788483 0.8161364  0.24277566]
 [0.45576556 0.99885538 0.55457892]]


In [15]:
import numpy as np
arr=np.array([[1,2,3,4.5],[5,6,7,8]])

print("Shape:",arr.shape)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)
print("size:",arr.size)
print("item size:",arr.itemsize)
#slicing
arr1 = np.array([10,20,30,40])
print("first element",arr1[0])

print("first element",arr1[-1])
print("slice[1:4]",arr1[1:4])
print("every second element",arr1[::2])

#indexing
arr2 = np.array([[1,2,35],[5,9,8]])
print("element at row 1, col 2",arr2[0,1])
print("second row",arr2[1,:])
print("second column",arr2[:,1])

Shape: (2, 4)
dimension: 2
data type: float64
size: 8
item size: 8
first element 10
first element 40
slice[1:4] [20 30 40]
every second element [10 30]
element at row 1, col 2 2
second row [5 9 8]
second column [2 9]


In [16]:
#mathematical functions
arr=np.array([0, np.pi/2, np.pi/3, np.pi])
print("sin values",np.sin(arr))
print("cos values",np.cos(arr))
print("cosine:",np.sqrt([1,4,9]))
print("exponential:",np.exp([1,2]))
print("logaritham:",np.log([1,np.e,np.e**2]))

sin values [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]
cos values [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]
cosine: [1. 2. 3.]
exponential: [2.71828183 7.3890561 ]
logaritham: [0. 1. 2.]


In [17]:
#aggregate fuctions
arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))
print("mean:",np.mean(arr))
print("standard deviation",np.std(arr))
print("sum along axis 0:",np.sum(arr,axis=0))  #column-wise sum
print("sum along axis 1:",np.sum(arr,axis=1))  #row-wise sum

sum: 21
min: 1
max: 6
mean: 3.5
standard deviation 1.707825127659933
sum along axis 0: [5 7 9]
sum along axis 1: [ 6 15]


In [18]:
#broadcasting
a=np.array([1,2,3])
b=5
print("add scalar to array:",a+b)#[6 7 8]
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("broadcasting:\n",c+d)

add scalar to array: [6 7 8]
broadcasting:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [21]:
#numerical computing basic with numpy
#matrix operations
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("matrix multiplication:\n",np.dot(a,b))
print("matrix transpose:\n",np.transpose(a))
print("matrix inverse:\n",np.linalg.inv(a))
print("determinant:",np.linalg.det(a))


matrix multiplication:
 [[19 22]
 [43 50]]
matrix transpose:
 [[1 3]
 [2 4]]
matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant: -2.0000000000000004


In [23]:
#student marks analsis
import numpy as np
#marks of students in 3 subjects
marks=np.array([
    [85,90,88],
    [78,81,85],
    [92,89,95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
