<a href="https://colab.research.google.com/github/Thotasaiteja2004/python-for-data-structures/blob/main/lan-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
print('list')
l=[10,99.9,"cse"]
for i in l:
    print(type(i),i)
li=[10,20,30,40]
print(li)
if 20 in li:
    print('found')
else:
    print('not found')
li.append(50)
print(li)
li.remove(30)
print(li)
li.insert(2,25)
print(li)
l.pop()
lis=[9,3,10,40,5,0]
lis.reverse()
print(lis)
lis.sort()
print(lis)
print(sum(lis))
print(max(lis))
print(min(lis))
student = [[10,30],[40,60],[70,80]]
print(student)
for i in student:
  print(*i)
  print("10\t 20\n30\t 40\n50\t 40")
l=[[10,20],[30,40],[50,60]]
print("\n",join "",join(mapPstr,i))for i in l

list
<class 'int'> 10
<class 'float'> 99.9
<class 'str'> cse
[10, 20, 30, 40]
found
[10, 20, 30, 40, 50]
[10, 20, 40, 50]
[10, 20, 25, 40, 50]
[0, 5, 40, 10, 3, 9]
[0, 3, 5, 9, 10, 40]
67
40
0
[[10, 30], [40, 60], [70, 80]]
10 30
10	 20
30	 40
50	 40
40 60
10	 20
30	 40
50	 40
70 80
10	 20
30	 40
50	 40


In [13]:
t=(10,20,30,40)
print(t)
t=(10,20,30,10,20)
print(t)
t=(10,99.9,"cse")
for i in t :
  print(type(i),i)
  if 20 in t:
    print("f")
else:
  print("not f")
  t =(1,2,3,2,3,2,4)
  print(t.count(2))
  print(t.index(4))



(10, 20, 30, 40)
(10, 20, 30, 10, 20)
<class 'int'> 10
<class 'float'> 99.9
<class 'str'> cse
not f
3
6


In [26]:
print("dictionary")
st={"name":"saitej","id":"1535","branch":"cse"}
print(st.keys())
print(st.values())
print(st.items())
for key,value in st.items():
  print(key,":",value)

dictionary
dict_keys(['name', 'id', 'branch'])
dict_values(['saitej', '1535', 'cse'])
dict_items([('name', 'saitej'), ('id', '1535'), ('branch', 'cse')])
name : saitej
id : 1535
branch : cse


In [31]:
print(set)
s={1,2,3,4}
print(s)
s={1,2,3,2,3,2}
print(s)
for i in s:
  print ("i")
if 2 in s:
  print("f")
else:
  A={1,2,3}
  B={2,3,4}
  print(A.union(B))
  print(A.intersection(B))
  print(A.difference(B))
  print(A.symmetric_difference(B))
s={1,2,3}
s.add(4)
print(s)
s.remove(2)
print(s)
s.clear()
print(s)

<class 'set'>
{1, 2, 3, 4}
{1, 2, 3}
i
i
i
f
{1, 2, 3, 4}
{1, 3, 4}
set()


In [33]:
import numpy as np
marks = np.array([
    [85, 78, 92],
    [67, 74, 81],
    [90, 88, 95],
    [56, 60, 65],
    [82, 79, 84]
])
average_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)
selected_students = marks[[1, 3], :]
high_scorers = marks[np.any(marks > 80, axis=1)]
subject_wise = marks.T
print("Average Marks:", average_marks)
print("Minimum Marks:", min_marks)
print("Maximum Marks:", max_marks)
print("Selected Students' Marks:\n", selected_students)
print("Students scoring above 80:\n", high_scorers)
print("Subject-wise Performance:\n", subject_wise)


Average Marks: [85.         74.         91.         60.33333333 81.66666667]
Minimum Marks: [78 67 88 56 79]
Maximum Marks: [92 81 95 65 84]
Selected Students' Marks:
 [[67 74 81]
 [56 60 65]]
Students scoring above 80:
 [[85 78 92]
 [67 74 81]
 [90 88 95]
 [82 79 84]]
Subject-wise Performance:
 [[85 67 90 56 82]
 [78 74 88 60 79]
 [92 81 95 65 84]]


In [36]:
import pandas as pd
data = {
    'Name': ['sai', 'sabir', 'Chandu', 'priya', 'thrishala'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing'],
    'Salary': [48000, 52000, 61000, 45000, 70000]
}
df = pd.DataFrame(data)
high_salary = df[df['Salary'] > 50000]
sorted_df = df.sort_values(by='Salary', ascending=False)
df['Bonus'] = df['Salary'] * 0.10
total_expense = df['Salary'].sum() + df['Bonus'].sum()
df.to_csv('employee_salary_bonus.csv', index=False)
print("Filtered (Salary > 50,000):\n", high_salary)
print("\nSorted by Salary:\n", sorted_df)
print("\nDataFrame with Bonus:\n", df)
print("\nTotal Expense (Salary + Bonus):", total_expense)


Filtered (Salary > 50,000):
         Name   ID Department  Salary
1      sabir  102         IT   52000
2     Chandu  103    Finance   61000
4  thrishala  105  Marketing   70000

Sorted by Salary:
         Name   ID Department  Salary
4  thrishala  105  Marketing   70000
2     Chandu  103    Finance   61000
1      sabir  102         IT   52000
0        sai  101         HR   48000
3      priya  104         IT   45000

DataFrame with Bonus:
         Name   ID Department  Salary   Bonus
0        sai  101         HR   48000  4800.0
1      sabir  102         IT   52000  5200.0
2     Chandu  103    Finance   61000  6100.0
3      priya  104         IT   45000  4500.0
4  thrishala  105  Marketing   70000  7000.0

Total Expense (Salary + Bonus): 303600.0
